project:
  type: website
  output-dir: docs

website:
  title: "Isabel Chang"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: extracurriculars.qmd
        text: Extracurriculars
      - href: research/research.qmd
        text: Research
      - href: travels.qmd
        text: Travels

format:
  html:
    theme: minty
    css: styles.css
    toc: true
    page-layout: full
    include-in-header:
      - text: |
          <link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css" />
          <script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"></script>

editor: visual

